### ISSUE TITLE
'freeze_modules_based_on_opts()' is freezing module parameters twice

### ISSUE THREAD

**Issue by hub-bla** [apple/corenet#11]
## Example
```
opts = argparse.Namespace(**{"model.freeze_modules": "conv1"})


model = nn.Sequential(
     OrderedDict([
          ('conv1', nn.Conv2d(20,64,5)),
          ('conv2', nn.Conv2d(20,64,5))
        ])
)


print(freeze_modules_based_on_opts(opts, model))
```
![example_result](https://github.com/apple/corenet/assets/56601011/6d47bc00-5bc9-4fbc-a874-faa1e8e8a130)

**Comment by mustafahadbe** [comment]
> ## Example
> ```
> opts = argparse.Namespace(**{"model.freeze_modules": "conv1"})
> 
> 
> model = nn.Sequential(
>      OrderedDict([
>           ('conv1', nn.Conv2d(20,64,5)),
>           ('conv2', nn.Conv2d(20,64,5))
>         ])
> )
> 
> 
> print(freeze_modules_based_on_opts(opts, model))
> ```
> 
> ![example_result](https://private-user-images.githubusercontent.com/56601011/326063696-6d47bc00-5bc9-4fbc-a874-faa1e8e8a130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzU4NjMsIm5iZiI6MTcxNDE3NTU2MywicGF0aCI6Ii81NjYwMTAxMS8zMjYwNjM2OTYtNmQ0N2JjMDAtNWJjOS00ZmJjLWE4NzQtZmFhMWU4ZThhMTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDIzNTI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4YmU1NDc3NTY4NzgyYzVkNDk5MWFlYjlhMjBmYzNlZDk1MzBiZDMyNGJiMDM2NTJlY2Y5NjcwYWI1NWI3ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhELsJO-DBVqrmFkcPoxGfJvhBlyPnrNQ6STmtsCleo)

``mu

**Comment by Mandeep0001** [comment]
GOT IT

**Comment by mohammad7t** [comment]
Freezing modules (i.e. disabling `.train()`) is different with freezing parameters (i.e. setting `requires_grad=False`). As this issue is closely related to #10 , I'm closing this one.
