### ISSUE TITLE
Why use interpreted language ?

### ISSUE THREAD

**Issue by AugustinMauroy** [apple/corenet#18]
Why use interpreted language ?  An interpreted language is slower and less powerful. You should use a compiled language such as c++.

For example I had work on [this project] in c++. 

You should definitely stop using interpreted language.

**Comment by mohammad7t** [comment]
Hi @AugustinMauroy ,

CoreNet is mainly intended for research and training, where the flexibility is an important requirement. If you have further questions about the best language for research and training, please consider asking questions on Q/A platforms, or searching for existing ones like https://ai.stackexchange.com/questions/36547/whys-and-why-nots-using-rust-for-ai.

**Comment by AugustinMauroy** [comment]
Hi @mohammad7t thanks for your answer !

First I want to clarify I'm not asking to change something. If I want a c++ version , all I have to do is do it myself. I'm just asking why.

And also sorry for the inconvenience.

BTW, super project

**Comment by mohammad7t** [comment]
No worries ! Stay curious
