### ISSUE TITLE
Request for Access to OpenELM Training Logs

### ISSUE THREAD

**Issue by Essoz** [apple/corenet#31]
Hi CoreNet team,

Thank you for your fantastic work on CoreNet and the OpenELM model. I've been trying to understand ML infrastructure reliability, and I'm particularly interested in analyzing the training logs that were mentioned in your OpenELM paper.

<img width="609" alt="image" src="https://github.com/apple/corenet/assets/31838999/afd1709e-d045-4c63-902f-7bf1197e0d24">

However, I've searched online and couldn't find these logs available anywhere. Could you please guide me on how to access these logs, or consider making them available if possible?

Access to these logs would be incredibly beneficial for my research, and I believe it could also be valuable for the community interested in understanding the nuances of ML model training at scale.

Thank you for your time and consideration.

**Comment by sacmehta** [comment]
Thank you for your interest in our work. Links to the training logs, checkpoints, and pre-training configurations are provided [here](https://github.com/apple/corenet/blob/main/projects/openelm/README-pretraining.md#model-weight-checkpoints). 

For your convenience, I have included them below.

| Iteration | OpenELM-270M | OpenELM-450M | OpenELM-1.1B | OpenELM-3B |
| ---- | ---- | ---- | ---- | ---- | 
| Training logs | [Link](https://docs-assets.developer.apple.com/ml-research/models/corenet/v0.1.0/openelm/pretrained/270M/training_logs.txt) | [Link](https://docs-assets.developer.apple.com/ml-research/models/corenet/v0.1.0/openelm/pretrained/450M/training_logs.txt) | [Link](https://docs-assets.developer.apple.com/ml-research/models/corenet/v0.1.0/openelm/pretrained/1.1B/training_logs.txt) | [Link](https://docs-assets.developer.apple.com/ml-research/models/corenet/v0.1.0/openelm/pretrained/3B/training_logs.txt) |

**Comment by Essoz** [comment]
Thank you so much for the prompt reply!!
