### ISSUE TITLE
How OpenELM 1.1B and larger LLMs are initialized during pre-training

### ISSUE THREAD

**Issue by sanyalsunny111** [apple/corenet#40]
Hi Authors,

I really appreciate you open sourcing the code and models of OpenELM. I am curious how you have initialized your 1.1B and larger OpenELM models for pre-training? I have tried looking into the paper as well but it doesn't have this info.

**Comment by mohammad7t** [comment]
Hi @sanyalsunny111,

The initialization is implemented in `reset_parameters()` method of all model classes, including GeneralGPT (that is used by OpenELM). For instance, please see https://github.com/apple/corenet/blob/2261885b6696950aaf481a862e8926921ef1a067/corenet/modeling/models/language_modeling/general_gpt.py#L765
