### ISSUE TITLE
where can I get checkpoints

### ISSUE THREAD

**Issue by sankexin** [apple/corenet#6]
hello, where is checkpoints?

**Comment by sacmehta** [comment]
Information about different OpenELM tasks is in this [README](https://github.com/apple/corenet/tree/main/projects/openelm). If you click on the individual task link, you will be directed to respective README files, which contain more information about the task including pre-training checkpoints. 

For example, OpenELM pre-training checkpoints are [here](https://github.com/apple/corenet/blob/main/projects/openelm/README-pretraining.md#pretraining-checkpoints-model-weights-and-logs).
